// Generated by gencpp from file godelbot/set_camera_mode.msg
// DO NOT EDIT!


#ifndef GODELBOT_MESSAGE_SET_CAMERA_MODE_H
#define GODELBOT_MESSAGE_SET_CAMERA_MODE_H

#include <ros/service_traits.h>


#include <godelbot/set_camera_modeRequest.h>
#include <godelbot/set_camera_modeResponse.h>


namespace godelbot
{

struct set_camera_mode
{

typedef set_camera_modeRequest Request;
typedef set_camera_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_camera_mode
} // namespace godelbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::godelbot::set_camera_mode > {
  static const char* value()
  {
    return "cd2737036405069bf2d76a05df1c316d";
  }

  static const char* value(const ::godelbot::set_camera_mode&) { return value(); }
};

template<>
struct DataType< ::godelbot::set_camera_mode > {
  static const char* value()
  {
    return "godelbot/set_camera_mode";
  }

  static const char* value(const ::godelbot::set_camera_mode&) { return value(); }
};


// service_traits::MD5Sum< ::godelbot::set_camera_modeRequest> should match 
// service_traits::MD5Sum< ::godelbot::set_camera_mode > 
template<>
struct MD5Sum< ::godelbot::set_camera_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::godelbot::set_camera_mode >::value();
  }
  static const char* value(const ::godelbot::set_camera_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::godelbot::set_camera_modeRequest> should match 
// service_traits::DataType< ::godelbot::set_camera_mode > 
template<>
struct DataType< ::godelbot::set_camera_modeRequest>
{
  static const char* value()
  {
    return DataType< ::godelbot::set_camera_mode >::value();
  }
  static const char* value(const ::godelbot::set_camera_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::godelbot::set_camera_modeResponse> should match 
// service_traits::MD5Sum< ::godelbot::set_camera_mode > 
template<>
struct MD5Sum< ::godelbot::set_camera_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::godelbot::set_camera_mode >::value();
  }
  static const char* value(const ::godelbot::set_camera_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::godelbot::set_camera_modeResponse> should match 
// service_traits::DataType< ::godelbot::set_camera_mode > 
template<>
struct DataType< ::godelbot::set_camera_modeResponse>
{
  static const char* value()
  {
    return DataType< ::godelbot::set_camera_mode >::value();
  }
  static const char* value(const ::godelbot::set_camera_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GODELBOT_MESSAGE_SET_CAMERA_MODE_H
