// Generated by gencpp from file godelbot/set_camera_modeRequest.msg
// DO NOT EDIT!


#ifndef GODELBOT_MESSAGE_SET_CAMERA_MODEREQUEST_H
#define GODELBOT_MESSAGE_SET_CAMERA_MODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace godelbot
{
template <class ContainerAllocator>
struct set_camera_modeRequest_
{
  typedef set_camera_modeRequest_<ContainerAllocator> Type;

  set_camera_modeRequest_()
    : mode(0)  {
    }
  set_camera_modeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;




  typedef boost::shared_ptr< ::godelbot::set_camera_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::godelbot::set_camera_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_camera_modeRequest_

typedef ::godelbot::set_camera_modeRequest_<std::allocator<void> > set_camera_modeRequest;

typedef boost::shared_ptr< ::godelbot::set_camera_modeRequest > set_camera_modeRequestPtr;
typedef boost::shared_ptr< ::godelbot::set_camera_modeRequest const> set_camera_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::godelbot::set_camera_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace godelbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'godelbot': ['/home/james/godelbot_ws/src/godelbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::godelbot::set_camera_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::godelbot::set_camera_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::godelbot::set_camera_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::godelbot::set_camera_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "godelbot/set_camera_modeRequest";
  }

  static const char* value(const ::godelbot::set_camera_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
uint8 mode\n\
";
  }

  static const char* value(const ::godelbot::set_camera_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_camera_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::godelbot::set_camera_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::godelbot::set_camera_modeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GODELBOT_MESSAGE_SET_CAMERA_MODEREQUEST_H
